steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - functions
      - deploy
      - identity-ocr
      - '--runtime=go119'
      - '--no-gen2'
      - '--entry-point=ocrIdentity'
      - '--trigger-http'
      - '--memory=128Mi'
      - '--timeout=60s'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$_GCP_PROJECT_ID'
      - '--set-env-vars'
      - 'OLLAMA_API=$_OLLAMA_API'
      - '--set-env-vars'
      - 'OLLAMA_ENDPOINT=$_OLLAMA_ENDPOINT'
      - '--set-env-vars'
      - 'OLLAMA_HOST=$_OLLAMA_HOST'
      - '--set-env-vars'
      - 'OLLAMA_KEY=$_OLLAMA_KEY'
      - '--set-env-vars'
      - 'SPACE_ENDPOINT=$_SPACE_ENDPOINT'
      - '--set-secrets'
      - 'OPENAI_API_KEY=openai-api-key:latest'
      - '--allow-unauthenticated'
    entrypoint: gcloud
timeout: 1200s
options:
  logging: 'CLOUD_LOGGING_ONLY'
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
